// Code generated by asset-hashes.
// sources:
// assets/commit.js
// assets/robots.txt
// assets/style.css
// DO NOT EDIT!

package main

import (
	"fmt"
	"os"
)

const _assetHashLength = 64

var _assetHashes = map[string]string{
	"assets/commit.js":  "87c6e7d8e6a7041eed85017be3192693719f8897670125c45bec6fcdde8ed883",
	"assets/robots.txt": "f4347e7481764549a05b77820e3ab4a468273afc3935613db92267b7b97670b1",
	"assets/style.css":  "1b0471015f022ec73f4c085b7c8317b35e8faa7f77bdf1dfa3551323747e548e",
}

func AssetHash(name string) (string, error) {
	if hash, ok := _assetHashes[name]; ok {
		return hash, nil
	}

	return "", fmt.Errorf("Asset %s not found", name)
}

func AssetHashName(name string) (string, error) {
	hash, err := AssetHash(name)
	if err != nil {
		return "", err
	}

	for i := len(name) - 1; i >= 0 && !os.IsPathSeparator(name[i]); i-- {
		if name[i] == '.' {
			return name[:i] + "-" + hash + name[i:], nil
		}
	}

	return name + "-" + hash, nil
}

func AssetNameStripHash(name string) (string, error) {
	for i := len(name) - 1; i >= 0 && !os.IsPathSeparator(name[i]); i-- {
		if name[i] != '.' {
			continue
		}

		if i-_assetHashLength-1 < 0 || name[i-_assetHashLength-1] != '-' {
			return "", fmt.Errorf("Asset %s not found", name)
		}

		hash, err := AssetHash(name[:i-_assetHashLength-1] + name[i:])
		if err != nil {
			return "", err
		}

		if name[i-_assetHashLength:i] != hash {
			return "", fmt.Errorf("Asset %s not found", name)
		}

		return name[:i-_assetHashLength-1] + name[i:], nil
	}

	i := len(name)

	if i-_assetHashLength-1 < 0 || name[i-_assetHashLength-1] != '-' {
		return "", fmt.Errorf("Asset %s not found", name)
	}

	hash, err := AssetHash(name[:i-_assetHashLength-1] + name[i:])
	if err != nil {
		return "", err
	}

	if name[i-_assetHashLength:i] != hash {
		return "", fmt.Errorf("Asset %s not found", name)
	}

	return name[:i-_assetHashLength-1] + name[i:], nil
}

func AssetFromNameHash(name string) ([]byte, error) {
	name, err := AssetNameStripHash(name)
	if err != nil {
		return nil, err
	}

	return Asset(name)
}

func AssetInfoFromNameHash(name string) (os.FileInfo, error) {
	name, err := AssetNameStripHash(name)
	if err != nil {
		return nil, err
	}

	return AssetInfo(name)
}
